name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Build & Deploy
        env:
            PASS_WORD: ${{secrets.SSH_PASSWORD}}
        run: |
            sshpass -p $PASS_WORD ssh -o StrictHostKeyChecking=no -i private_key dotien@tiennt-server.duckdns.org -p 22 '
              cd skill.v3.api &&
              git pull &&
              docker-compose down &&
              docker rmi swd-backend_backend:latest &&
              docker-compose up --build -d
              '
