name: Deploy to My Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:

    - name: SSH and Run Command
      uses: actions/checkout@v4 
      with:
        key: ${{ secrets.SSH_PASSWORD }}
        script: |
          # Replace `your_command` with the actual command you want to run on the server.
          ssh dotien@tiennt-server.duckdns.org "
          cd skill.v3.api && 
          git pull && 
          docker-compose down && 
          docker rmi swd-backend_backend:latest && 
          docker-compose up --build -d
          "
